In [1]:
a = 5
print (type (a))

b=9.6
print (type (b))

<class 'int'>
<class 'float'>


In [2]:
# 1-D = array method from array module = no problem
# 2-D = array method from array module = error
# 2-D = list inside another list = possible to use 
# 2-D = array method from numpy module = possible to use = ndarray (n-dimension array)

a = ([
[1,2,3],
[4,5,6],
[7,8,9],
])
print (a)
print (type(a))
print (a[2][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
8


In [4]:
print (len(a)) # list inside a list will be an element
for i in range(len(a)):
    for j in range(len(a)): # 0 to 2
        print (a[i][j], end=" ")
    print ("\n")

3
1 2 3 

4 5 6 

7 8 9 



In [5]:
print (type (a))

<class 'list'>


In [14]:
import array as tr
#ar = tr.array("i",[[1,2,4], [5,6,7]]) # error use list
ar = tr.array("i",[[6,7,8],[8,9,10]])
print (ar)
print (type(ar))

TypeError: an integer is required (got type list)

In [16]:
import numpy as tr
#ar = tr.array("i",[[1,2,4], [5,6,7]]) # error use list
ar = tr.array([[6,7,8],[8,9,10]]) #do not need to use data type mode "i", "b"
print (ar)
print (type(ar))

[[ 6  7  8]
 [ 8  9 10]]
<class 'numpy.ndarray'>


In [31]:
import numpy as vc
a = vc.array ([7,2,5,6,9,7,6,2,4,6,3])
print (a)
print (len(a))

b = vc.partition (a, 5)
print (b)

[7 2 5 6 9 7 6 2 4 6 3]
11
[3 2 2 4 5 6 6 6 7 9 7]


In [1]:
# type - is used to represent data type of a variable
a = 90
b = 78.34
c = "Virendra"

print (type (a))
print (type (b))
print (type (c))

<class 'int'>
<class 'float'>
<class 'str'>


In [2]:
ar1 = [34, 56, 78, 12, 89, 24, 75, 41]
print (ar1)
print (type (ar1))

[34, 56, 78, 12, 89, 24, 75, 41]
<class 'list'>


In [3]:
import array as tr
ar1 = [34, 56, 78, 12, 89, 24, 75, 41] # ar1 - list variable
ar2 = tr.array ("i", ar1) # ar2 - array variable
print (ar1)
print (type (ar1))
print (ar2)
print (type (ar2))

[34, 56, 78, 12, 89, 24, 75, 41]
<class 'list'>
array('i', [34, 56, 78, 12, 89, 24, 75, 41])
<class 'array.array'>


In [4]:
td = [[1,2,3], [4,5,6], [7,8,9]]
print (td)
print (type (td))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [6]:
import array as tdr
#ar3 = tdr.array ("i", td) # error
ar3 = tdr.array ("i", [[3,4], [5,6]])
print (ar3)
print (type(ar3))

TypeError: an integer is required (got type list)

In [8]:
import numpy as tdr
ar3 = tdr.array (td) #data type mode is not required
#ar3 = tdr.array ("i", [[3,4], [5,6]])
print (ar3)
print (type(ar3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [9]:
# 1-D = array method from array module = no problem
# 2-D = array method from array module = error
# 2-D = list inside another list = possible to use 
# 2-D = array method from numpy module = possible to use = ndarray (n-dimension array)


In [1]:
# WAP to create two matrices and print those.
first = [[4,6,8,9], [7,8,2,3], [9,1,7,5]]
second = [[6,8,2,9], [1,7,4,8], [7,3,3,0]]
print (first)
print (second)
print (first + second)

import numpy as vsk
far = vsk.array (first)
sar = vsk.array (second)
print (far)
print (len(far))
print (sar)
print (far + sar)

[[4, 6, 8, 9], [7, 8, 2, 3], [9, 1, 7, 5]]
[[6, 8, 2, 9], [1, 7, 4, 8], [7, 3, 3, 0]]
[[4, 6, 8, 9], [7, 8, 2, 3], [9, 1, 7, 5], [6, 8, 2, 9], [1, 7, 4, 8], [7, 3, 3, 0]]
[[4 6 8 9]
 [7 8 2 3]
 [9 1 7 5]]
3
[[6 8 2 9]
 [1 7 4 8]
 [7 3 3 0]]
[[10 14 10 18]
 [ 8 15  6 11]
 [16  4 10  5]]


In [4]:
# addition of first and second array named by far and sar
res = [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
add = vsk.array (res)
for i in range (3): # total 3 rows
    for j in range (4):  # total 4 columns
        #print (i , j)
        add[i][j] = far[i][j] + sar[i][j]
        #print (far[i][j] + sar[i][j], end = " ")
    print ("\n")
print (add)







[[10 14 10 18]
 [ 8 15  6 11]
 [16  4 10  5]]


In [31]:
# Partitioning of an array by using numpy library
import numpy as vsk
in_arr = vsk.array([2,3,4,7,12,1,9,23,45,67,21,9,3,4])
print (len(in_arr))
print (in_arr)

14
[ 2  3  4  7 12  1  9 23 45 67 21  9  3  4]


In [35]:
import numpy as p
m = p.array ([12, 10, 20, 30, 22, 24, 26, 12, 27, 10, 54])
print (m)
print (type (m))
print (len (m))
res = p.partition (m, 7)
print (res)

[12 10 20 30 22 24 26 12 27 10 54]
<class 'numpy.ndarray'>
11
[12 12 20 10 22 10 24 26 27 30 54]


In [14]:
# Program to multiply two matrices using nested loops
A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]
result = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
print(result)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]
